Update method of downloading the MaxMind GeoIP, addressing #3529
cvuosalo/cvmfs pull request #1
Opened 2024-04-01 22:32 UTC by cvuosalo

This merge request addresses issue https://github.com/cvmfs/cvmfs/issues/3529 -- the need to update `cvmfs_server` because MaxMind is changing the API for GeoIP database downloads. The new method requires the account ID.

`cvmfs` administrator documentation will have to be changed to say that the new variable `CVMFS_GEO_ACCOUT_ID` needs to be added to` /etc/cvmfs/server.local`. The administrator will need to check their MaxMind account to get their account ID.

These changes were tested to verify that the `cvmfs_server update-geodb` command successfully downloads the database file by the new method. Testing also confirms the command will now fail if `CVMFS_GEO_ACCOUT_ID` is not configured.

2024-04-02 19:29 UTC, DrDaveD requested changes
Also update test/src/595-geoipdbupdate/main.

I can show you how to run the test when you're ready to try it.

2024-04-02 19:29 UTC, DrDaveD commented on cvmfs/server/cvmfs_server_util.sh
> +  if [ -z "$CVMFS_GEO_ACCOUT_ID" ]; then
Typo.  Should be `CVMFS_GEO_ACCOUNT_ID`

2024-04-05 20:14 UTC, DrDaveD approved these changes
Looks ok, although it says there's a conflict so would need to rebase it.

Oh, and they prefer to have PRs against the stable branch for for things going into a patch release. Currently that's `cvmfs-2.11`.

2024-04-05 22:09 UTC, cvuosalo commented
I copied this PR to a new PR #3566 against the cvmfs_2.11 branch. Closing this PR.

2024-04-05 22:09 UTC, closed without merging